### ISSUE TITLE
Thoughts about the current specification

### ISSUE THREAD

**Issue by Profpatsch** [SFTtech/nyan#1]
English translation below.

Habe mal meine Gedanken während des Lesens der Spec runtergeschrieben. Sind linear entstanden, also es war noch nicht für jeden Kommentar alle Information vorhanden. Mehr so ein Gedankendump. :)

* Generell nicht so überzeugt von Vererbung zur Darstellung von Daten (Diamantenabhängigkeit = Teufels Küche)
* Warum einen Unterschied zwischen Patches und Objekten an sich machen?
* +1 Namespaces
* Wie patcht man etwas, wenn man die anderen Patches eventuell nicht sieht und nicht kontrollieren kann? In welcher Reihenfolge werden die Patches dann angewandt?
* Warum sind alle Values Maybe-Typen?
* Was heißt Strongly typed? Ein paar Primitives? Generics? Higher-Order-Types? :)
* += bei Inheritance heißt, dass die Daten doch Logik enthalten (nur halt versteckt)
* Wie wird die Liste an Patches aufgebaut? Welcher Patch hat Priorität? Was passiert bei Clash?
* +1 Gut auf die Anforderungen des Spiels zugeschnitten
* Unit hierarchy wird sehr schnell an die Grenzen stoßen. Was passiert, wenn Archer zwar eine Ranged Unit ist, aber noch einen Bonus b bekommt, wenn er von der Rasse Mensch ist? Für eine solche Geschichte würde ich ein Entity Component System anwenden. https://en.wikipedia.org/wiki/Entity_component_system  
http://gamedevs.org/uploads/data-driven-game-object-system.pdf  
* Bei den Beispielen bin ich mir nicht mehr so sicher, ob es nicht doch bereits ein Entity Component System ist oder zumindest abbilden kann.
* `MoveAbility` wird noch nicht mit `instant: bool` definiert sein, weil die Engineentwickler nicht daran denken, dass es mal gebraucht wird. Wenn jetzt bereits existierende Units teleportieren können sollen, muss man eine `MoveAbilityInstant` Gschichte definieren, die nur `instant: bool` enthält. Wenn eine bereits existierende Einheit jetzt teleportieren können soll, muss man sie erst für MoveAbilityInstant instantiieren, damit man sie für Teleport instantiieren kann.
  Nach einiger Überlegung definiert ihr im Endeffekt hier Typklassen (die Vererbung beinhalten), aber *auch* Datentypen mit Vererbung. Das könnte zu lustigen Effekten führen, Haskell hat sich z.B. absichtlich dafür entschieden, dass Datentypen *keine* Vererbung beinhalten, da man sonst nur noch sehr wenig kontrollieren kann / das Typchecking echt lustig wird.
  Eine weitere Überlegung, die man machen sollte, sind sogenannte “orphan instances” (Typklassen-Lingo). Das bedeutet, dass man die Instanz eines Typen nicht in einem Modul definieren kann, das nicht die Typklasse oder den Typen definiert.
* Wie wird dann im Endeffekt Logik gemacht? (Funktionen sind übrigens auch „nur“ Datentypen und Code is Data. :P)

----
English translation of my braindump (wrote it in a linear fashing while reading through the spec):

* generally not very convinced about using inheritance to represent data (diamond-shaped subclasses = hell)
* Why differentiate between `patches` and `objects`?
* +1 namespaces
* How to patch something if one doesn’t know about the other patches that will get applied? What order to apply these patches in?
* Why are all types Maybe-types (that is: values are optional?)
* What does strongly typed mean? Some primitives? Generics? Higher-order types? :)
* += combined with inheritance means the files *do* contain some logic (but hidden)
* How to build up a list of patches? What patch is prioritized? What happens on conflict?
* +1 well suited to the requirements of OpenAge
* Unit hierarchy will hit its limits pretty fast. For example, what happens when Archer is a ranged unit, but a bonus should be applied if its race is Human?
Personally I’d try to implement an Entity Component System https://en.wikipedia.org/wiki/Entity_component_system  
  http://gamedevs.org/uploads/data-driven-game-object-system.pdf  
* When I look at the examples, I’m not sure anymore whether nyan maybe does already implement some kind of CES, or at least can be used to represent one
* `MoveAbility` won’t be intitially defined with the `instant: bool` field, because developers won’t think about it being needed later. If one now wants existing units to be able to implement `Teleport`, one has to implement something like `MoveAbilityInstant` which only contains the field `instant: bool`; the previously mentioned unit will now instantiate MoveAbilityInstant and then Teleport
  After some thinking I came to the conclusion that nyan basically defines typeclasses (which contain inheritance by default), but data types with inheritance *as well*. That could lead to interesting effects; Haskell has deliberately decided that data types should *not* have any inheritance, because it’s very hard to control stuff otherwise / typechecking gets really … interesting (cf. Scala)
  Another thing that should be considered are “orphan instances”, where an instantiation of a typeclass for a type is forbidden in a module that does not at least contain the definition of the type or the typeclass.
* In the end, how is logic for the data implemented? (functions are also only data types btw, and code = data. :P)

**Comment by TheJJ** [comment]
Would be awesome if you could translate your stuff into english as most of the people don't understand german here :)

**Comment by Profpatsch** [comment]
> most of the people don't understand german here

Pffffffff

Why am I doing this … anyway

**Comment by TheJJ** [comment]
> generally not very convinced about using inheritance to represent data (diamond-shaped subclasses = hell)

diamond is impossible because the enforced qualification of conflicting members. the inheritance is required to allow whole unit classes to be updated, e.g. "all infantry has +2 armor now".

> Why differentiate between `patches` and `objects`?

A patch is an object. But we explicitly disallow to apply an non-patch object as patch because it's not assigned to a target. It makes the validity check possible at creation-time of the patch.

> How to patch something if one doesn’t know about the other patches that will get applied? What order to apply these patches in?

You can only create a patch for something you know, see above. The apply order is up to the game engine, it can either do automatic mod ordering or you the user sorts it manually.

> Why are all types Maybe-types (that is: values are optional?)

We need to be able to define a member and make it available for use for members that set a value. For example, all units have a HP member, their value is unknown. The engine must rely on the existence of that member, but the value is then set by `Villager` or something.

> What does strongly typed mean? Some primitives? Generics? Higher-order types? :)

It means all modifications to members can only be done with operators and values allowed for that type. One member has a type declaration that can never be changed, so an int member can never store a string.

> += combined with inheritance means the files do contain some logic (but hidden)

Jup, the value calculation is not just a return of some memory. It must aggregate all the values from all parents that set some value up to the first parent that does `=`.

> Unit hierarchy will hit its limits pretty fast. For example, what happens when Archer is a ranged unit, but a bonus should be applied if its race is Human?

Then archer must either be inheriting from `Human` in the first place or a mod patch adds the `Human` parent to `Archer` as a patch. Then, if `Human` is patched, archer will get that update as well. **But** that is a totally different thing, when adding some new ability, the ability set is extended by a patch and this probably equals the entity component system. How that components are used is of course up to the engine.

> When I look at the examples, I’m not sure anymore whether nyan maybe does already implement some kind of entity component system, or at least can be used to represent one

Jup, it's possible. Even with an arbitrary amount of component containers.

> MoveAbility won’t be intitially defined with the instant: bool field, because developers won’t think about it being needed later.

Yes, but if they forget to implement it in the engine, it is impossible to use as a mod. Even with an infinite speed it would use the pathfinding, which wrong when teleporting.

> In the end, how is logic for the data implemented?

Uh, what logic?

**Comment by fr3akout** [comment]
Actually you will run into the diamond problem. Assume the following inheritance hierarchy:
```
Unit():
    health_points: int

RangedUnit(Unit):
    ranged_damage: int

MeleeUnit(Unit):
    melee_damage: int

SpecialUnit(MeleeUnit as melee, RangedUnit as ranged):
    melee.health_points = 100
    ranged.health_points = 50
```
To solve this you need some kind of linearization. I would recommend [C3 linearization](https://en.wikipedia.org/wiki/C3_linearization) which is used by python as well.

**Comment by Profpatsch** [comment]
> But we explicitly disallow to apply an non-patch object as patch because it's not assigned to a target.

I suggest treating everything as Patch and to make `Foo()` syntactic sugar for `Foo(Empty)`, where `Empty` is the empty Patch.

> We need to be able to define a member and make it available for use for members that set a value. For example, all units have a HP member, their value is unknown.

So values are not really optional, are they? The type checker should only accept non-abstract data, which means every field must be set.

> += combined with inheritance means the files do contain some logic (but hidden)
> Jup, the value calculation is not just a return of some memory. It must aggregate all the values from all parents that set some value up to the first parent that does =.

Which directly contradicts the goal of not having any logic in your data, stated at the beginning of the spec …

> or a mod patch adds the Human parent to Archer as a patch.

This sounds like a lot of “fun”. I cannot say I understand the implications of this being possible at all, but I don’t think they are going to make dealing with the patch system very pleasant.

> Uh, what logic?

What is the interface for the programmer to use the data in the scripting language?

**Comment by TheJJ** [comment]
> I suggest treating everything as Patch and to make Foo() syntactic sugar for Foo(Empty), where Empty is the empty Patch.

Hm maybe, but that's some internal implementation detail. Let's see if it makes sense when we reach that point :)

>> We need to be able to define a member and make it available for use for members that set a value. For example, all units have a HP member, their value is unknown.

> So values are not really optional, are they? The type checker should only accept non-abstract data, which means every field must be set.

Nah, values are optional. A mod can extend the mod API by adding objects with members but without values. Other mods can then extend those objects and set values. The type checker is able to verify the hierarchy as the type is always required and set, just the value is optional.

> Which directly contradicts the goal of not having any logic in your data, stated at the beginning of the spec …

Maybe, but it's not turing complete either, which is what nyan is explicitly avoiding. The evaluation is some kind of logic, but it's required to do the hierarchical patching required for openage.

> This sounds like a lot of “fun”. I cannot say I understand the implications of this being possible at all, but I don’t think they are going to make dealing with the patch system very pleasant.

We just allow it, and it's easy to implement. The implications of that are pretty unknown to me as well, the type check is still able to detect any errors, so that features is very cheap to add and potentially very powerful. Some mod can change a unit to be both cavalry and infantry, for example.

**Comment by Profpatsch** [comment]
> Hm maybe, but that's some internal implementation detail. Let's see if it makes sense when we reach that point :)

Nah, it’s exactly the contrary, a fundamental API decision.

> Nah, values are optional. A mod can extend the mod API by adding objects with members but without values. Other mods can then extend those objects and set values.

This seems pretty undisciplined to me.

> The type checker is able to verify the hierarchy as the type is always required and set, just the value is optional.

So the type checker actually checks for a sum type of `Value | Null`, which is a commonly recommended against method these days.

**Comment by TheJJ** [comment]
>> Hm maybe, but that's some internal implementation detail. Let's see if it makes sense when we reach that point :)

> Nah, it’s exactly the contrary, a fundamental API decision.

You're probbaly right, a patch is now a regular object with an `__patch__` member, see the updated spec.

>>  Nah, values are optional. A mod can extend the mod API by adding objects with members but without values. Other mods can then extend those objects and set values.

> This seems pretty undisciplined to me.

Why is it undisciplined? We need abstract objects so that mods are required to override some value. When it already has a value, the member can be ignored. In the openage standardlib most of the fields will be defaulted, so this is up to the engine implementation once again.

> `Value | Null`

When there's no value, I can't check it's type. The type hierarchy is always checked as there is always a member type.

See also the updated spec on multi inheritance. Also, I implemented the first parser and AST generator.

**Comment by TheJJ** [comment]
Much has changed now, if you like, you may review the updated spec again :)
