### ISSUE TITLE
Make failed on macOS: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by baijifeilong** [SFTtech/nyan#50]
The build fails on macOS:

```
[100%] Linking CXX executable nyancat
Undefined symbols for architecture x86_64:
  "nyan::Number<long long>::apply_value(nyan::Value const&, nyan::nyan_op)", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::allowed_operations(nyan::Type const&) const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::str() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::copy() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::hash() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::repr() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::equals(nyan::Value const&) const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [nyan/nyancat] Error 1
make[1]: *** [nyan/CMakeFiles/nyancat.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TheJJ** [comment]
I guess there is a missing virtual destructor for either nyan::Number or one of its base classes.

**Comment by tusharpm** [comment]
Just checked: the members functions for `nyan::Int` and `nyan::Float` are not instantiated.
This surfaced in the debug build. To see it in optimised builds, call `.str()` for a `nyan::Int` object.

_Possible solution:_ [instantiate the member functions](https://en.cppreference.com/w/cpp/language/function_template#Function_template_instantiation) by
- explicit instantiation, or
- implicit instantiation.

I made [some changes](https://github.com/SFTtech/nyan/compare/master...tusharpm:gh_issue_50) demonstrating both options.
The reason for choosing either option pertains to a few characteristics of the function itself - like the implementation details, size (roughly in loc), etc. I chose explicit instantiation for `apply_value` and `allowed_operations` because they use non-`std` types in their definition.

Please let me know if I should send a PR instead.

**Comment by TheJJ** [comment]
Okay, I'd appreciate if you PR'd it, so we can fix this bug :)
