### ISSUE TITLE
Dict and dict operations

### ISSUE THREAD

**Issue by MaanooAk** [SFTtech/nyan#68]
For openage dicts will be very useful in order to deal with what in the engine are called `ResourceBundle`.

In nyan creating a set of something like ResourceAmount would be very verbose, but with `dict(Resource, float)` a collection of resources can encoded very nicely:

``` python
Unit():
    cost : dict(Resource, float)

Knight(Unit):
    cost = {Food: 70, Gold: 75}
```

However, there is a need to be able to access the dict values separately. I would suggest something like that:

``` python
CheaperKnights<Knight>():
    cost[Gold] -= 20
```

Sidenote: Time (training time) could also be modeled as a Resource and be included in the cost

**Comment by TheJJ** [comment]
i was always unsure about adding a dict-type, because it may have &lt;gmanvoice&gt; *unforseen consequences* &lt;/gmanvoice&gt;:
Currently you can implement dicts by using a set of objects, and the objects then have some values. Those objects are always referencable, as they have a name. Thus they can always be patched. ~~When we add a real key-value type, values can get lost.~~ If `valueType` is an object, the object is always referencable. Non-object values can get lost when it is updated in the dict. Which may not be desirable.

I guess that we should add dicts, though. Intuitively they seem a good addition, and loosing non-object values is probably okay, because who cares for a `"random string"` or a number like `235`. If you overwrite it, you likely won't revert.

So all in all I think you are right and we should add a dict-type.

**Comment by MaanooAk** [comment]
Yes but its huge

``` python
Something():
    FoodCost(ResourceAmount):
        resource: Food
        amount: 50
    WoodCost(ResourceAmount):
        resource: Wood
        amount: 50
    cost: {FoodCost, WoodCost}
```

My first thought was some kind of an anonymous object, but then you have something that cannot be referenced so why not just dicts.

Also having a bunch of prebuild WoodCost50, WoodCost75 but again you cannot patch them.

Maybe having a way to inline it, but then it gets ugly...

**Comment by TheJJ** [comment]
Yea indeed, so let's go for `dict` :)
